version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api/backend:/home/app
    depends_on:
      - postgres
    networks:
      vpcbr:
        ipv4_address: 172.168.1.5

  samba:
      container_name: samba
      image: dperson/samba
      environment:
        TZ: 'EST5EDT'
      networks:
        vpcbr:
          ipv4_address: 172.168.1.4
      ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
        - "445:445/tcp"
      read_only: true
      tmpfs:
        - /tmp
      restart: unless-stopped
      stdin_open: true
      tty: true
      volumes:
        - /mnt:/mnt:z
        - /mnt2:/mnt2:z
      command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "willi;nique" -p'

  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "salope"
      PGDATA: "/data/postgres"
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.168.1.3
    
  front:
    container_name: frontend
    build:
      context: ./httpd
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.168.1.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.168.1.1/24
         gateway: 172.168.1.1