version: '3'

services:
  # samba:
  #     container_name: samba
  #     image: dperson/samba
  #     environment:
  #       TZ: 'EST5EDT'
  #     networks:
  #       vpcbr:
  #         ipv4_address: 172.168.1.4
  #     ports:
  #       - "137:137/udp"
  #       - "138:138/udp"
  #       - "139:139/tcp"
  #       - "445:445/tcp"
  #     read_only: true
  #     tmpfs:
  #       - /tmp
  #     restart: unless-stopped
  #     stdin_open: true
  #     tty: true
  #     volumes:
  #       - /mnt:/mnt:z
  #       - /mnt2:/mnt2:z
  #     command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "willi;nique" -p'

  db:
    container_name: db
    image: "postgres:12"
    volumes:
       - ./postgres:/data/postgres
    restart: always
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=db
    networks:
      vpcbr:
        ipv4_address: 172.168.1.3
  api:
    container_name: api
    build:
      context: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./api/backend:/home/app
    depends_on:
      - db
    links:
      - db
    networks:
      vpcbr:
        ipv4_address: 172.168.1.6
  front:
    container_name: frontend
    build:
      context: ./httpd
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.168.1.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.168.1.1/24
         gateway: 172.168.1.1